# Generated by Django 5.0.6 on 2024-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                ("cid", models.AutoField(primary_key=True, serialize=False)),
                ("cname", models.CharField(max_length=200)),
                ("clocation", models.CharField(max_length=200)),
                ("totalstudent", models.IntegerField()),
                ("numdepartment", models.IntegerField()),
            ],
        ),
    ]
